POST http://localhost:5000/auth
Content-Type: application/json

{
  "email": "mai@mail.com",
  "password": "123" 
}

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "mi@mail.com",
  "password": "123" 
}




